# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : "Kandice Lu"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Kandice Lu"
description              : "Kandice Lu - Projects and CV"
baseurl                  : "" # Set this to "portfolio-<your-github-username>" 
url                      : "https://kandicelu.github.io/"# the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

# Theme and Style
theme: minima
color_scheme: light # light/default, dark, or aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
 # pages:
    #output: true
  projects:
    output: true
    permalink: /projects/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

